#!/bin/sh

LETSENCRYPT_ENV=${LETSENCRYPT_ENV:-staging}

cat /etc/rancher-conf/haproxy/state.yml \
  | yq r -j - \
  | jq '.entries[]
    | (.containers[]?.ingress[]?.domains[]? |= { domain: . })
    | .containers[]? |= (.ingress[]?.domains[]?.container = { health, state, ip })
    | .containers[]?
    | .ingress[]? |= (.domains[]?.frontend = .frontend)
    | .ingress[]? |= (.domains[]?.container.port = .port)
    | .ingress[]?
    | .domains[]?' \
  | jq -s 'group_by(.frontend.name)[]
    | {
        frontend: .[0].frontend,
        domains: [(group_by(.domain.id)[]? | {
          domain: .[0].domain,
          containers: [ .[]? | .container ]
        })] | sort_by((.domain.prefix // "") | length) | reverse
      }
    | (.frontend.certfile = (if .frontend.certfile == "letsencrypt" then ("/etc/rancher-conf/haproxy/" + .frontend.name + "-" + "'"$LETSENCRYPT_ENV"'" + ".pem") else .frontend.certfile end))' \
  | jq -s '.' \
  | yq r - \
  | yq p - frontends \
  > /etc/rancher-conf/haproxy/haproxy.yml

yq r /etc/rancher-conf/haproxy/state.yml defaults \
  | yq p - defaults \
  | yq w -i -s - /etc/rancher-conf/haproxy/haproxy.yml

yq r /etc/rancher-conf/haproxy/state.yml global \
  | yq p - global \
  | yq w -i -s - /etc/rancher-conf/haproxy/haproxy.yml

yq r /etc/rancher-conf/haproxy/state.yml health \
  | yq p - health \
  | yq w -i -s - /etc/rancher-conf/haproxy/haproxy.yml

yq r /etc/rancher-conf/haproxy/state.yml stats \
  | yq p - stats \
  | yq w -i -s - /etc/rancher-conf/haproxy/haproxy.yml

gotpl /etc/rancher-conf/templates/haproxy.cfg.tmpl \
  < /etc/rancher-conf/haproxy/haproxy.yml \
  > /etc/rancher-conf/haproxy/.haproxy.cfg

/etc/rancher-conf/scripts/check-haproxy /etc/rancher-conf/haproxy/.haproxy.cfg \
  && mv /etc/rancher-conf/haproxy/.haproxy.cfg /etc/rancher-conf/haproxy/haproxy.cfg \
  && /etc/rancher-conf/scripts/reload-haproxy
