#!/bin/sh

if [[ "$S3_BUCKET" != "" ]]; then
  SOURCE_PATH="${S3_BUCKET}/${S3_PREFIX}"
  CERT_DIR=${S3_MOUNT_DIR:-/s3/$SOURCE_PATH}
else
  CERT_DIR=${CERT_DIR:-/etc/rancher-conf/haproxy}
fi

CERT_NAME=${CERT_NAME:-haproxy.rancher.cert}
LETSENCRYPT_ENV=${LETSENCRYPT_ENV:-staging}

UUID=$(yq r -j /etc/rancher-conf/haproxy/state.yml uuid | jq -r .)
LEADER=$(yq r -j /etc/rancher-conf/haproxy/state.yml leader | jq -r .)

touch /etc/rancher-conf/haproxy/next-sync

now=$(date '+%s')
next=$(cat /etc/rancher-conf/haproxy/next-sync)
if [[ "$next" == "" ]]; then
  next='0'
fi

echo $now $next

if [ $next -ge $now ]; then
  echo 'waiting for next sync'
  exit 0
else
  date --date='2 minutes' '+%s' > /etc/rancher-conf/haproxy/next-sync
fi

if [[ "$LEADER" == "$UUID" ]]; then
  # Update/renew certificate if necessary

  DOMAINS=$(cat /etc/rancher-conf/haproxy/state.yml \
    | yq r -j - \
    | jq -r '.entries[] | .containers[] | .ingress[] | .domains[] | .host' \
    | sed 's/[^.]*/*/' \
    | sort \
    | uniq \
    | xargs -I{} echo -n "-d {} ")

  CMD="certbot certonly \
    --config-dir ${CERT_DIR} \
    --cert-name ${CERT_NAME} \
    --dns-route53 \
    --keep-until-expiring \
    --expand \
    --renew-with-new-domains \
    --dry-run \
    --deploy-hook /etc/rancher-conf/scripts/reload-haproxy"

  if [[ "${LETSENCRYPT_EMAIL}" != "" ]]; then
    CMD="$CMD --noninteractive --agree-tos --email ${LETSENCRYPT_EMAIL}"
  fi

  if [[ "$LETSENCRYPT_ENV" != "production" ]]; then
    CMD="$CMD --staging"
  fi

  echo "$CMD $DOMAINS"
  $CMD $DOMAINS

  cat ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem ${CERT_DIR}/live/${CERT_NAME}/privkey.pem > ${CERT_DIR}/live/${CERT_NAME}/combined.pem

  if [[ "$S3_BUCKET" != "" ]]; then
    s3-push
  fi
else
  # Pull the latest certificate
  if [[ -e ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem ]]; then
    current=$(date -r ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem '+%s')
  else
    current="0"
  fi

  if [[ "$S3_BUCKET" != "" ]]; then
    s3-pull
  fi

  if [[ -e ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem ]]; then
    updated=$(date -r ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem '+%s')
  else
    updated="0"
  fi

  if [ $updated -ge $current ]; then
    /etc/rancher-conf/scripts/reload-haproxy
  fi
fi

