#!/bin/sh

CERT_DIR=${CERT_DIR:-/etc/rancher-conf/haproxy/certs}
CERT_NAME=${CERT_NAME:-haproxy.rancher.cert}
LETSENCRYPT_ENV=${LETSENCRYPT_ENV:-staging}

UUID=$(yq r -j /etc/rancher-conf/haproxy/state.yml uuid | jq -r .)
LEADER=$(yq r -j /etc/rancher-conf/haproxy/state.yml leader | jq -r .)

touch /etc/rancher-conf/haproxy/next-sync.timestamp

now=$(date '+%s')
next=$(cat /etc/rancher-conf/haproxy/next-sync.timestamp)
if [[ "$next" == "" ]]; then
  next='0'
fi

echo $now $next

if [ $next -ge $now ]; then
  echo 'waiting for next sync'
  exit 0
else
  date --date='2 minutes' '+%s' > /etc/rancher-conf/haproxy/next-sync.timestamp
fi

mkdir -p $CERT_DIR

if [[ "$LEADER" == "$UUID" ]]; then
  # Update/renew certificate if necessary

  DOMAINS=$(cat /etc/rancher-conf/haproxy/state.yml \
    | yq r -j - \
    | jq -r '.entries[] | .containers[] | .ingress[] | .domains[] | .host' \
    | sed 's/[^.]*/*/' \
    | sort \
    | uniq \
    | xargs -I{} echo -n "-d {} ")

  CMD="certbot certonly \
    --config-dir ${CERT_DIR} \
    --cert-name ${CERT_NAME} \
    --dns-route53 \
    --keep-until-expiring \
    --expand \
    --renew-with-new-domains \
    --deploy-hook /etc/rancher-conf/scripts/reload-haproxy"

  if [[ "${LETSENCRYPT_EMAIL}" != "" ]]; then
    CMD="$CMD --noninteractive --agree-tos --email ${LETSENCRYPT_EMAIL}"
  fi

  if [[ "$LETSENCRYPT_ENV" != "production" ]]; then
    CMD="$CMD --staging"
  fi

  $CMD $DOMAINS

  cat ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem ${CERT_DIR}/live/${CERT_NAME}/privkey.pem > /etc/rancher-conf/haproxy/cert.pem
else
  version=$(cat /etc/rancher-conf/haproxy/last-reload.timestamp)
  if [[ "$version" == "" ]]; then
    version='0'
  fi

  if [[ -e /etc/rancher-conf/haproxy/cert.pem ]]; then
    current=$(date -r ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem '+%s')
  else
    current='0'
  fi

  if [ $current -ge $version ]; then
    cat ${CERT_DIR}/live/${CERT_NAME}/fullchain.pem ${CERT_DIR}/live/${CERT_NAME}/privkey.pem > /etc/rancher-conf/haproxy/cert.pem
    date '+%s' > /etc/rancher-conf/haproxy/last-reload.timestamp
    /etc/rancher-conf/scripts/reload-haproxy
  fi
fi

